parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2022: true
  browser: true

extends:
  - eslint:recommended
  - prettier

plugins:
  - prettier

rules:
  # Prettier
  'prettier/prettier': 'error'
  
  # Ошибки
  'no-unused-vars': 'error'
  'no-undef': 'error'
  'no-console': 'warn'

  # Переменные
  'no-var': 'error'
  'prefer-const': 'error'

  # Функции
  'func-style': ['error', 'expression']
  'prefer-arrow-callback': 'error'

  # Игнорировать @ директивы в SCSS
  'no-unused-expressions': 'off'
