parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2022: true
  browser: true

extends:
  - eslint:recommended

rules:
  # Ошибки
  'no-unused-vars': 'error'
  'no-undef': 'error'
  'no-console': 'warn'

  # Стиль кода
  'indent': ['error', 2]
  'quotes': ['error', 'single']
  'semi': ['error', 'always']
  'comma-dangle': ['error', 'never']

  # Стрелочные функции
  'arrow-spacing': 'error'
  'arrow-parens': ['error', 'always']

  # Переменные
  'no-var': 'error'
  'prefer-const': 'error'

  # Функции
  'func-style': ['error', 'expression']
  'prefer-arrow-callback': 'error'
